version: “3.8”
services:
  server:
    image: node
    ports:
      - 3050:3050
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4y7sV96vA9wv46VR
      POSTGRES_DB: SDC
    ports:
      - ‘5432:5432’
    volumes:
      - /var/lib/postgres/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080